### ISSUE TITLE
XML Provided by tabroom

### ISSUE THREAD

**Issue by Sweets** [Sweets/judge-variance#1]
The XML doesn't seem to have any `BALLOT_SCORE` tags anymore, do you have an older copy so that I can take a look at it?

(XML as in the file retrieved from https://www.tabroom.com/api/tourn_published.mhtml?tourn_id=9335&event_id=79402)

@borao

**Comment by borao** [comment]
I can once I'm in front of my computer, but something else: can we make this in PHP? The org is using a PHP site so I planned to run a Flask server to host this, but it seems like that's going to be much more resource intensive. If you're familiar enough/would like to do it, let me know so I can make a boilerplate.

**Comment by Sweets** [comment]
Yeah sure thing. I'm seasoned in php, so it shouldn't be too much trouble.

**Comment by borao** [comment]
That's great! Then can you fork the original (borao/judge-variance, not ocdl/judge-variance) and PR some php boilerplate? I can supply any data as needed, but the file I put above gets the same thing as the URLs.

**Comment by borao** [comment]
Also, to fork the original, you might need to delete this fork. The reason why I ask is because merging PRs was kind of strange with the fork in between...

**Comment by borao** [comment]
Actually, let's maybe put the PHP on hold. I have an idea but it's kind of complicated so I'll describe it when I see you.

**Comment by borao** [comment]
Can you please close the issue? It's showing up in my dashboard.
